lib/vagrant-openshift/action/generate_template.rb

Same issue as addressed in openshift/origin@fa4579e3266c4dd715ecc9b0346cd33fc2bd1d58
Empty lines in `~/.awscred` caused the `Array` passed to the `Hash`
constructor to have an odd number of elements, raising an exception. Now
lines are `strip!`ped before `split`ting, and `flatten` discards the empty
`Array`(s) produced as a result.

Accommodate empty lines in ~/.awscred

---

README.asciidoc

Should be "`src/github.com/...`", was "`github.com/src/...`"

Fix path typo in README.asciidoc

---

README.asciidoc
lib/vagrant-openshift/action.rb
lib/vagrant-openshift/action/generate_template.rb
lib/vagrant-openshift/command/repo_sync_openshift3.rb
lib/vagrant-openshift/templates/command/init-openshift/box_info.yaml

Remove v2 instructions entirely and point to v3 Vagrantfile.
Stop telling people to edit Vagrantfile to use other providers.
Add --no-images flag to sync-openshift3

docs: update and improve for other providers and starting images

---

lib/vagrant-openshift/command/test_openshift3_image.rb

Now the command will be compatible with sti images in which different versions of platform/db are placed in different subfolders.
eg. sti-nodejs  -> https://github.com/openshift/sti-nodejs
If the `version` is not present the command assumes that the Dockerfile is in the root of the repository.

Update test_openshift3_image cmd for STI images

---

lib/vagrant-openshift/command/test_openshift3_image.rb
lib/vagrant-openshift/constants.rb

There is a new ruby-20 image(ruby-20-centos7) and we are going to get rid of the old one(ruby-20-centos)

Updating image name and github repo link

---

lib/vagrant-openshift/action.rb
lib/vagrant-openshift/action/push_openshift3_images.rb
lib/vagrant-openshift/command/push_openshift3_images.rb
lib/vagrant-openshift/constants.rb
lib/vagrant-openshift/plugin.rb

Usage:
```
vagrant push-openshift3-images --registry=<url>:5000
```
This command will do following with each 'image' repository we have (nodejs, ruby, ...):
1. git clone image repository
2. get git short ref
3. docker pull registry/image_name:GIT_SHORT_REF
4. if image is found then noop, if not found (returns 1) then:
5. make build (builds the image)
6. docker tag registry/image_name:GIT_SHORT_REF
7. docker push registry/image_name:GIT_SHORT_REF

Added push_openshift3_images

---

lib/vagrant-openshift/constants.rb

@bparees we don't need to clone all images repos during the checkout as we are not building them locally, just fetching them from the Hub.
We should also be pulling the latest images from the private registry, not from the hub (in all other jobs). This will make us independent from the Hub builder issues.

Remove openshift images from checkout

---

lib/vagrant-openshift/action/push_openshift3_images.rb
lib/vagrant-openshift/constants.rb

The summary of what this PR do:
* If the base image (either base-rhel7 or base-centos7) changes, all images are rebuilt and pushed no matter if they were update or not. 
* Send notification with summary of what images were updated and how you can pull them.
* Build all RHEL7 images and push them to the private registry

Added support for RHEL7 for all Docker images

---

lib/vagrant-openshift/action.rb
lib/vagrant-openshift/action/install_openshift3_router.rb
lib/vagrant-openshift/action/run_systemctl.rb
lib/vagrant-openshift/command/install_openshift3_router.rb
lib/vagrant-openshift/plugin.rb

Install router as part of doing an install-openshift3.
Changes:
1.  Ensure the install command does a build and starts the service
2.  Add an action that will check for openshift in a running state and run the install command for a default router.  Action should skip installation if default router already exists.
3.  Change try-restart to restart.  Try restart does nothing if the service is not already running.

install router as part of installing openshift 3

---

lib/vagrant-openshift/action/install_openshift3.rb
lib/vagrant-openshift/action/install_openshift3_router.rb

`osc` switched to only respect OPENSHIFTCONFIG, not KUBECONFIG.
@liggitt I didn't see another location using this.

change KUBECONFIG to OPENSHIFTCONFIG

---

lib/vagrant-openshift/action/install_openshift3.rb

Files are moving due to openshift/origin#1737 and we have significant drift from reality. This brings us back into alignment.
Do not merge until openshift/origin#1737 goes in.

handle cert flattening

---

lib/vagrant-openshift/action/install_openshift.rb

@danmcp - the default ulimit of 1024 is far too low when you start working with larger number of objects, or when etcd does a snapshot.
bumping it up to 4096 has shown me no problem.
Fixes https://github.com/openshift/origin/issues/3202

Increase ulimit to 4096

---

lib/vagrant-openshift/command/test_openshift_image.rb

Since we are using the `make test` for testing images and testing all the versions, we no longer need the `image_version` option

Removing unnecessary option

---

lib/vagrant-openshift/action/run_openshift_tests.rb
lib/vagrant-openshift/command/test_openshift.rb

Adds a `--extended` flag to `vagrant test-openshift` to specify that you want extended tests run.  This won't do anything unless specified, but if you want it to run you'll need https://github.com/openshift/origin/pull/4033.
@liggitt ptal

add support for extended tests

---

lib/vagrant-openshift/action/download_artifacts_openshift.rb

@bparees the vagrant-openshift change to include the extended test artifacts in the archive.zip download from Jenkins

gather extended test data for artifacts download

---

lib/vagrant-openshift/action/run_sti_tests.rb

@bparees the vagrant plugin change for the sti --run=true test, once that merge is through

add test-stirunimage.sh test

---

lib/vagrant-openshift/action.rb
lib/vagrant-openshift/action/atomic_host_upgrade.rb
lib/vagrant-openshift/command/build_atomic_host.rb
lib/vagrant-openshift/plugin.rb

@danmcp @detiber @brenton 
Currently the repo is registered in the AMIs so all that is required is doing an atomic host upgrade.
CI jobs will be needed to update the images accordingly I will put a trello card in for that.

Upgrade atomic host on AMIs

---

lib/vagrant-openshift/action/install_openshift_base_dependencies.rb

@liggitt @bparees @derekwaynecarr 
`go get` will always fetch the latest `HEAD`, so it seems in order to version-lock the tool we should just `git checkout` as was pointed out to me on #go-nuts. Thoughts?

version lock go vet

---

README.asciidoc

Installing `NOKOGIRI_USE_SYSTEM_LIBRARIES=1` seems most often than not recommended given compiling everything from source is more error prone especially on non-linux and generally less secure compared to using system libraries that are usually updated more often.
Added info about the new options `OSFloatingIP` and `OSFloatingIPPool`

more details to openstack instructions

---

lib/vagrant-openshift/action/run_openshift_tests.rb
lib/vagrant-openshift/command/test_openshift.rb

Adds a `-j` flag to run `make` with the `-j` flag for parallelism.  The intent is for this to be `false` by default while we see how much it helps and how stable it is on jenkins.
@jwforres ptal

run make -j test

---

lib/vagrant-openshift/action/install_openshift_base_dependencies.rb

We need/want these for ldap group sync extended tests.  `vagrant build-openshift-base` ran successfully for me. See "deads-install-prereq-check" instance. 
@jwforres

add openldap-clients and jq

---

lib/vagrant-openshift/action/download_artifacts_openshift.rb
lib/vagrant-openshift/action/download_artifacts_sti.rb

We're already seeing too many show up, makes it harder
to debug builds.
@danmcp this makes it much easier to debug failures - anyone
changing this can reenable verbose for debugging.

Download doesn't need to be verbose on artifacts

---

lib/vagrant-openshift/action/push_openshift_images.rb
lib/vagrant-openshift/action/run_sti_tests.rb
lib/vagrant-openshift/command/test_origin_image.rb

This is needed for https://github.com/openshift/source-to-image/pull/331 to pass and merge and for further s2i images tests.
@bparees ptal

Updated s2i paths to point to new build location

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb

fixes https://github.com/openshift/origin/issues/5869
@danmcp are you ok with having the packages on multiple lines?
it makes it better for reading what gets installed, and it also avoids creating duplicates.
hg, tmux and vim were added there twice.
can we also update the kernel-* files they're pretty outdated (3.17.4-301) and the latest for f21release are (4.1.10-100) ? i noticed they're skipped on yum update

added kernel-devel, removed duplicate packages and sorted

---

lib/vagrant-openshift/action/run_origin_tests.rb
lib/vagrant-openshift/command/test_origin.rb

For images that are expensive to build (like dind) and change rarely, a
registry can serve as a cache to minimize the cost of test setup.

Support configuring testing with an image registry

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb

It no longer compiles on master for 1.4.  This was causing the script to exit.
The rest of the original workaround still works if we ignore the exit code with
this change.

Another Go vet workaround for 1.4

---

lib/vagrant-openshift/action/download_artifacts_origin.rb

This PR begins to address https://github.com/openshift/origin/issues/5843.
I add `/tmp/openshift/origin` as a target for download. Once this is rolled into the AMI we use for tests, I'll reconfigure all tests to use this new structure. 
What else needs to be updated that uses the artifacts downloaded?
@danmcp @bparees PTAL

add new download target for tmpdirs

---

lib/vagrant-openshift/action/install_origin_asset_dependencies.rb

Make sure we don't cache a bad asset install to prevent https://github.com/openshift/origin/issues/6651 from happening again

Test assets before backing them up

---

lib/vagrant-openshift/action/download_artifacts_origin.rb

Integration tests don't get anything downloaded right now, which is  bug.
Once https://github.com/openshift/origin/pull/6591 merges things will be much easier and I'll come back to clean this up.
@bparees PTAL

added integration test artifact downloading

---

lib/vagrant-openshift/action/run_origin_tests.rb
lib/vagrant-openshift/command/test_origin.rb

Add --targets (for Makefile execution on tests) and --root (whether
to invoke sudo on the tests). Change tests to default to using not-sudo.
Will be used to help address openshift/origin#6799 by having the jenkins job directly execute specific make targets.

Allow makefile targets, use root consistently

---

lib/vagrant-openshift/action/download_artifacts_origin.rb

We need two `--exclude=` stanzas as `rsync` uses blobbing instead of regex.
@bparees PTAL
@deads2k FYI
fixes https://github.com/openshift/vagrant-openshift/issues/390

blacklisted /volumes/ from rsync download

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb

The Kube iSCSI volume driver requires iscsiadm to be installed

Add iscsi utils to tests

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb

@bparees This bumps the version of `go vet` we are using on Jenkins to that which we use on Travis. We may need to look into how to marry the version that runs on Jenkins and on Travis, as that drift is not desireable.

bump go vet version

---

lib/vagrant-openshift/command/test_origin.rb

#372 neglected to include a word in the argument specification that would allow a registry argument to be provided.

Fix the --image-registry arg to test-origin

---

README.asciidoc
lib/vagrant-openshift/action.rb
lib/vagrant-openshift/action/checkout_repositories.rb
lib/vagrant-openshift/action/clean.rb
lib/vagrant-openshift/action/clone_upstream_repositories.rb
lib/vagrant-openshift/action/download_artifacts_origin_aggregated_logging.rb
lib/vagrant-openshift/action/local_origin_checkout.rb
lib/vagrant-openshift/action/run_origin_aggregated_logging_tests.rb
lib/vagrant-openshift/action/sync_local_repository.rb
lib/vagrant-openshift/command/download_artifacts_origin_aggregated_logging.rb
lib/vagrant-openshift/command/local_origin_setup.rb
lib/vagrant-openshift/command/repo_sync_origin_aggregated_logging.rb
lib/vagrant-openshift/command/test_origin_aggregated_logging.rb
lib/vagrant-openshift/constants.rb
lib/vagrant-openshift/plugin.rb

adds the commands sync-origin-aggregated-logging and
test-origin-aggregated-logging, and adds support for a
`--repo origin-aggregated-logging` argument to origin-local-checkout
and a couple of other commands.

add support for origin-aggregated-logging

---

lib/vagrant-openshift/action/run_origin_tests.rb

removes hard-coded paths that lead to incorrect locations after the Origin tmpdir update
for https://github.com/openshift/vagrant-openshift/pull/411
@danmcp

updated artifact paths

---

lib/vagrant-openshift/action/download_artifacts_origin.rb

@danmcp these are useless after the tmpdir changes in Origin

removed dead download links

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb
lib/vagrant-openshift/action/run_origin_tests.rb

Also, stop passing it to the non-extended tests, since only the extended
tests should be interacting with an external registry.

Pass OPENSHIFT_TEST_IMAGE_REGISTRY to extended tests

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb

Incoming extended tests will require an XFS filesystem mounted with gquota to
pass. Create a partition for /tmp/openshift where test data lands, including
the volume directory.

Create logical volume for openshift tests.

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb

Because we're now creating this structure here, we need to make sure the
ssh_user can still work within it.
Assuming tests run as ssh_user this should work. After a test run of build-origin-base:
```
$ vagrant ssh
Last login: Sat Mar  5 20:00:10 2016 from cpe-107-15-149-49.nc.res.rr.com
[centos@ip-172-18-15-171 ~]$ ll /tmp
total 2236
-rw-r--r--. 1 root   root   2278361 Jun  8  2015 chromedriver_linux64.zip
drwxr-xr-x. 2 root   root        17 Mar 10 13:24 hsperfdata_root
-rw-r--r--. 1 root   root      1745 Nov  6  2008 linux_signing_key.pub
drwxr-xr-x. 3 centos centos      24 Mar 10 13:26 openshift
-rwx--x--x. 1 centos centos     459 Mar 10 13:20 vagrant-shell
[centos@ip-172-18-15-171 ~]$ ll /tmp/openshift
total 0
drwxr-xr-x. 2 centos centos 6 Mar 10 13:26 xfs-vol-dir …
```

Fix permissions on /tmp/openshift.

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb

Previous location (/tmp/openshift/xfs-vol-dir) was being hidden by some element
of the test scripts that later mounts /tmp to a tmpfs.
Move to a separate location out of that tree and chown to the correct user.
Tested in EC2 and looks good.

Move XFS volume dir to /mnt.

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb

The previous attempt at whitelisting was only targeting OPTIONS=.*
instead of both that and OPTIONS='.*'

Fix whitelisting for ci.dev.openshift.redhat.com

---

lib/vagrant-openshift/action.rb
lib/vagrant-openshift/action/download_artifacts_origin.rb
lib/vagrant-openshift/command/download_artifacts_origin.rb
lib/vagrant-openshift/command/test_origin.rb

Adds new flags to Origin tests and artifact download to make release artifact download optional.
@bparees PTAL
@danmcp FYI
Thoughts on making this seamless - no AMI build missing artifacts? Should we just time this update correctly? Or should there be a pull first that allows the new flags but does nothing, so we can update the Jenkins job to use the flags, then push out this change to make the flag necessary to download artifacts?

make downloading release artifacts optional

---

README.asciidoc

We're using ASCIIDoc for the README but some of the formatting wasn't correctly showing up on GitHub. Unless we're publishing this somewhere else as well, we should not use syntax the GitHub rendering engine doesn't understand.
@danmcp @bparees

formatting fixes

---

lib/vagrant-openshift/action/generate_template.rb
lib/vagrant-openshift/command/origin_init.rb

This adds the `--required-tags` option to `origin-init`, which allows
callers to add one or more AWS tags for matching when selecting template
images.

origin-init: add option to check for AWS tag(s)

---

lib/vagrant-openshift/action/create_yum_repositories.rb

`epel-release-7-5.noarch.rpm` is no longer available from the EPEL repos, it's been replaced with `epel-release-7-6.noarch.rpm`. non-Fedora base AMI builds will fail until this is updated.

Update epel-release version

---

lib/vagrant-openshift/helper/command_helper.rb

@jwforres found failures in the merge queue were caused by reusing old vagrant instances already marked as _terminate
This removes directories (-d) and untracked files (-x) to get the repo back to a pristine state

Remove any existing vagrant artifacts when reusing git repo

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb

@danmcp this adds the repo for the rhel7 Go 1.6 build (targeted for 7.3) so that Centos7 and Fedora 23/24 can use it in Origin.
Manually tested on all 3 OS's, no problems hit.

Pull in openshift-rhel7-dependencies for Go 1.6

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb

@danmcp @dgoodwin @bparees PTAL / FYI
this is part 1 of as 2 step process to increase the allocation of the registry's xfs volume to ~5G
once this change is in and operating for our ci.openshift jenkins jobs, i'll then create the origin pull to update test/extended/setup.sh to increase the quota for the registry accordingly

allocate 5G to registry xfs vol

---

lib/vagrant-openshift/helper/command_helper.rb

In order to mangle the output of test scripts less,
all test calls to machine.communicator.{sudo,execute}
now pass :error_key => :ssh_bad_exit_status_muted, so
the errors that are printed by Vagrant do not contain
the command that was run, stderr, or stdout. The test
commands we are running will report this information
themselves by using the Origin stacktrace functions.
@danmcp PTAL
Fixes #461

Muted SSH exit status errors on test commands

---

Gemfile

Addresses a problem where more recent vagrant versions require a newer version of `bundler` than what's available in RHEL RPM `rubygem-bundler`

workaround so bundler will run with Ruby 2.0.0

---

README.asciidoc

- mention ability to just yum install vagrant-libvirt on recent Fedora installs
- removes long winded TLS configuration details - these are unnecessary, a simple addition to libvirt group should be adequate

Clarify and simplify libvirt instructions

---

lib/vagrant-openshift/helper/command_helper.rb

cleans up local tags that no longer exist in the `origin` remote
needed to fix https://github.com/openshift/origin/issues/10795

prune tags that no longer exist in origin

---

.travis.yml
Gemfile
README.asciidoc

Corrects the usermod command syntax, as it will fail with the following message:
`usermod: group '-a' does not exist`
The correct syntax should be `usermod -a -G libvirt $USER`
Replaces git:// with https:// in Gemfile 
Removed default version of bundler on travis-ci and replaces with 1.12.5 which is needed by the vagrant gem

updating usermod command syntax so that command does not fail

---

README.asciidoc

- updating instructions to specify using bundler 1.12.5 for building the gem
- adding "--provider=virtualbox" under virtualbox instructions to be more specific, as vagrant on my machine did not use it as the default
- emphasizing the use of 'sudo yum install vagrant-libvirt' and only install the vagrant-libvirt plugin as a last resort
- fixing formatting issue to put <github username> all on one line

updating instructions for working on the gem and a few other small issues

---

hack/test.sh
hack/update.sh

In order to allow for pull requests to the vagrant-openshift
repository to modify the tests run in the CI job, the tests
are now in the repository. Furthermore, pull request authors
will be able to run the tests locally during development.
@danmcp forgot I reconfigured this -- this is a prereq for the other two PRs

Migrated test script to the repository from the Jenkins job

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb

@benjaminapetersen will use this in his `hack/test-headless.sh` work.
/cc @danmcp @jwforres 

Add `xrandr` dependency to allow headless tests to poll for their display

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb

When choosing a program to poll for readiness of a display, it
looks like `xdpyinfo` is superior to `xrandr` as it makes few
assumptions about the host and seems to be compatible with all
of the operating systems that we want to run web console tests
on in headless mode.

Install the X11 utilities instead of the X11 server utilities

---

lib/vagrant-openshift/action/install_origin_asset_dependencies.rb

Use a headless server to run web console unit tests in dependency install

---

lib/vagrant-openshift/helper/command_helper.rb

`git gc` leaves 2 weeks of refs by default, but with a heavily-used repo
that means loads of "`dangling commit`" messages in the git fsck output.
Adding `--prune=all` cleans up all commits, so we should only get one or
a couple of dangling commits in the output on the next run.

add `--prune=all` to `git gc`

---

lib/vagrant-openshift/action/run_origin_asset_tests.rb

Instead of assuming things about how the web console wants
to run their test suites, we should instead simply run their
appropriate `make` target and let the repository define that
in whatever way they want.
@spadgett @danmcp @jwforres

Use a `make` target to run web console tests

---

lib/vagrant-openshift/action/push_openshift_images.rb

we don't need to do this anymore because we trigger a force rebuild when the registry is pruned.

don't force building of base image

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb
lib/vagrant-openshift/resources/configure_docker.sh
lib/vagrant-openshift/resources/configure_system.sh
lib/vagrant-openshift/resources/dockerextra.repo
lib/vagrant-openshift/resources/install_chrome.sh
lib/vagrant-openshift/resources/install_dependencies.sh
lib/vagrant-openshift/resources/install_dockerextra_repo.sh
lib/vagrant-openshift/resources/install_golang.sh
lib/vagrant-openshift/resources/install_nonessential.sh
lib/vagrant-openshift/resources/install_rhaos_repos.sh
lib/vagrant-openshift/resources/origin-deps-rhel7.repo
lib/vagrant-openshift/resources/reconfigure_network_fedora.sh
lib/vagrant-openshift/resources/rhaos31.repo
lib/vagrant-openshift/resources/rhaos32.repo
lib/vagrant-openshift/resources/rhaos33.repo
lib/vagrant-openshift/resources/rhaos34.repo

The code that supports `build-origin-base` was becoming unwieldy, so to
allow for easy modification and maintenance, it will be refactored to run
local scripts on the machine. The scripts are packaged with the plugin.
The first step of this command now is to copy all the available scripts
to the machine. The workflow for running scripts is shown in the refactor
of the network configuration script in this commit.
Signed-off-by: Steve Kuznetsov skuznets@redhat.com
@danmcp PTAL

Configure `build-origin-base` to use local scripts

---

lib/vagrant-openshift/action/run_origin_tests.rb

In order for users to parameterize their extended test runs using
vagrant-openshift, we need to allow the `vagrant test-origin --env`
environment variables to be honored for all test runs, not just
the non-extended ones.
/cc @gabemontero @jupierce 
@danmcp PTAL

Allow for users to pass environment variables to extended tests

---

lib/vagrant-openshift/action/run_origin_tests.rb

A valid extended test bucket name should never contain any
special shell characters, so it is unnecessary to attempt
to escape them. Similarly, the only characters inside of a
focus string that we are vulnerable to are double-quotes.
Extended test focuses should not contain literal double
quotes, so we should not need to escape anything in those
either.
fixes https://github.com/openshift/vagrant-openshift/issues/476
@bparees @danmcp PTAL

Remove shell-word escaping from extended test execution code

---

lib/vagrant-openshift/action.rb
lib/vagrant-openshift/action/run_customer_diagnostics_tests.rb
lib/vagrant-openshift/command/repo_sync_customer_diagnostics.rb
lib/vagrant-openshift/command/test_customer_diagnostics.rb
lib/vagrant-openshift/constants.rb
lib/vagrant-openshift/plugin.rb

The customer diagnostics team is prototyping a test suite written in go for
testing ansible-based tooling.  Right now we're still in the early stages so a
fork of openshift-ansible is being used.  If things go well by the end of the
sprint we expect to merge this to openshift-ansible and at that time we'd
update the urls accordingly.
The goal with these new commands is simply to enable a test and merge workflow
that matches other Origin teams.  The implementation is almost entirely similar
to the other sync and test commands that we have.

Customer Diagnostics commands

---

lib/vagrant-openshift/resources/install_dependencies.sh

This binary is necessary for certificate tests in Origin's
`test-cmd.sh` suite.

Added `openssl` as a base dependency for Origin

---

lib/vagrant-openshift/action.rb

Now that we require environments to have a specific version of Docker
and/or Golang installed, one that is not guaranteed to be the latest
version available, we must not do broad `yum update` actions after the
dependency installation step is complete. With a properly functioning
system, all stages of the VM images are published at regular intervals
and it is unlikely that the versions of base dependencies in these
images will lag significantly behind what is available in repositories.
We can therefore achieve the `yum update` by simply consuming newer
image stages as they become available.

Removed `yum update` step from Origin installation

---

lib/vagrant-openshift/action.rb
lib/vagrant-openshift/action/build_sti_base_windows.rb
lib/vagrant-openshift/action/clone_upstream_repositories.rb
lib/vagrant-openshift/action/download_artifacts_sti.rb
lib/vagrant-openshift/action/generate_template.rb
lib/vagrant-openshift/action/run_sti_tests.rb
lib/vagrant-openshift/aws.rb
lib/vagrant-openshift/command/build_sti_base_windows.rb
lib/vagrant-openshift/helper/command_helper.rb
lib/vagrant-openshift/hooks/configure_aws.rb
lib/vagrant-openshift/hooks/find_ami.rb
lib/vagrant-openshift/hooks/windows_wait.rb
lib/vagrant-openshift/plugin.rb
lib/vagrant-openshift/provisioner/configure_docker_client_windows.rb
lib/vagrant-openshift/provisioner/configure_docker_server_linux.rb
lib/vagrant-openshift/templates/command/init-openshift/box_info.yaml

- add 'build-sti-base-windows' vagrant command to build windows AMI with required prereqs
- hooks to enable simplification of Vagrantfile (auto-discover AMI id, auto-configure standard Vagrantfile parameters for AWS)
- hook to wait for Windows instance to report ready after sysprep
- provisioners to allow a Windows instance to be autoconfigured to reasonably securely use Docker on a helper RHEL instance
- miscellaneous fixes
@bparees 
@stevekuznetsov

Enable s2i windows testing

---

lib/vagrant-openshift/action/build_origin_base_images.rb

This avoids the issue of having to backport the script to branches that lack the script.  Building the images is an optimization for jobs that run all the time, so branches will still work without it so long as the build doesn't error out due a missing script.
cc: @smarterclayton

Build dind images only if build script is present

---

lib/vagrant-openshift/action/create_yum_repositories.rb

Instead of pinning the EPEL installation to a specific RPM and version
from a download, we should install EPEL using the `epel-release` package
available in `yum`.

Install EPEL using the `epel-release` package

---

lib/vagrant-openshift/resources/configure_docker.sh

Instead of configuring the logical volumes by hand, we should now use
the docker-storage-setup tool instead. The manual process is no longer
honored by Docker 1.12.6+. The ratio of data to metadata in the logical
volume is not identical to the ratio previously, but no compelling
reasons are known for which the default from docker-storage-setup
would be inappropriate.
Additionally remove any setup of docker-storage before calling 
docker-storage-setup.

Reconfigure Docker thin-pool setup to use `docker-storage-setup`

---

lib/vagrant-openshift/resources/install_dependencies.sh

@stevekuznetsov this is required for https://github.com/openshift/origin/pull/13585 to pass the `godep restore` test.
Long story short... We are not going to build Origin with these libraries as CGO deps as we will have special build tag that will disable it.. However, `godep` is stupid and it will try to compile the `containers/images` which will result in compilation error and test failure...
So.. this is only needed to fix that test. After this merge, I guess I will have to kick new base_ami build.

Add gpgme and libassuan to install dependencies

---

lib/vagrant-openshift/action/install_origin.rb

Nothing in the `hack/install-etcd.sh` script requires root privileges
and using them was causing other issues with unrelated scripts by
mucking up the ownership and permissions on shared directories. We just
install `etcd` without `sudo`.
[test]

Install `etcd` without using root privileges

---

hack/test.sh
lib/vagrant-openshift/helper/command_helper.rb

`git fsck` is very CPU-intense on large complex repos (like
openshift/origin). This change uses `git status` to check repo
viability instead, hopefully ameliorating the serious performance
issues we've been seeing in Jenkins.

`git status` instead of `git fsck` for performance

---

hack/test.sh

There is no contract that `docker-1.12.2` will remain available in the
given repository, so we should update the test to be less specific and
point at a repository where we know docker will live.
/cc @dobbymoodge [test]

Update docker installation test to be less specific

---

hack/test.sh
lib/vagrant-openshift/action.rb

In the past we were relying on default behavior when a null was passed
as the repository to sync when syncing source-to-image. This patch makes
that repository specification explicit.

Pass S2I name explicitly instead of relying on null behavior

---

lib/vagrant-openshift/action.rb

In the past we were relying on default behavior when a null was passed
as the repository to sync when syncing the Origin repo. This patch makes
that repository specification explicit.

Pass Origin name explicitly instead of relying on null behavior

---

lib/vagrant-openshift/action.rb
lib/vagrant-openshift/command/install_origin.rb

Many jobs need to install Origin but do not need to install the Origin
Web Console asset dependencies as they do not run the Web Console tests
and only consume the Web Console via the vendored bindata.
/cc @jwforres PTAL

Add a flag to disable asset install on Origin install

---

lib/vagrant-openshift/action.rb
lib/vagrant-openshift/command/repo_sync_customer_diagnostics.rb
lib/vagrant-openshift/command/repo_sync_jenkins.rb
lib/vagrant-openshift/command/repo_sync_origin.rb
lib/vagrant-openshift/command/repo_sync_origin_console.rb
lib/vagrant-openshift/command/repo_sync_origin_metrics.rb
lib/vagrant-openshift/command/repo_sync_sti.rb
lib/vagrant-openshift/plugin.rb

Removing a lot of the duplication between the different repo sync
commands allows us to add one for the Jenkins repo with minimal effort.
It would be nice to have a `vagrant sync-repo [REPO]` command but this
would be a breaking change for the CLI, so we can continue with the
named commands per repo instead.
@dobbymoodge @bparees PTAL
/cc @gabemontero not entirely sure how Jenkins was getting synced  over in the past, but we can use `vagrant sync-jenkins` after this patch lands

DRY out repo sync logic, add Jenkins sync
