openshift/vagrant-openshift

lib/vagrant-openshift/command/test_openshift3_image.rb

The new STI testing framework (part of https://trello.com/c/d845L5f1/445-5-sti-local-test-operation).
The standard way to run the STI image test framework is to execute `test/run` command.

Use new STI local image testing

---

lib/vagrant-openshift/action/install_openshift3.rb

Start vagrant in http for now

---

lib/vagrant-openshift/action/run_openshift3_tests.rb

Use make targets for unit, int, and e2e tests so they can be maintained in a single place.

convert tests to use make

---

lib/vagrant-openshift/constants.rb

Fix: Updating image name for ruby-2.0

---

lib/vagrant-openshift/command/test_openshift3_image.rb

Now the images are going to be build and tested with their STI test framework. Both CentOS7 and Rhel7 images are build and tested.

Update image test job

---

lib/vagrant-openshift/action/push_openshift3_images.rb

Need to add GIT tag into Docker Hub so we can check if the latest master is present there.

Fix tagging on Docker Hub

---

lib/vagrant-openshift/action/push_openshift3_images.rb

@bparees ok, so this should make this job **much** faster :-)

Make checking if Docker images exists faster

---

lib/vagrant-openshift/command/test_openshift3_image.rb

Refactoring

---

lib/vagrant-openshift/constants.rb

Adding MongoDB image into build/push process

---

lib/vagrant-openshift/constants.rb

Add PostgreSQL image to openshift3_images

---

lib/vagrant-openshift/command/test_openshift3_image.rb

Fix missing RHEL7 based test

---

lib/vagrant-openshift/command/test_openshift3_image.rb

Removing dockerd -H config argument

---

lib/vagrant-openshift/action/install_openshift3.rb

Just a change to allow better timeout on certificate creation.

Timeout on openshift start.

---

lib/vagrant-openshift/constants.rb

Build Perl images

---

lib/vagrant-openshift/action/yum_update.rb

Install deltarpm to reduce the download size from yum update.

Install deltarpm before yum update

---

Gemfile

@danmcp Dan - here is the vagrant-openshift Gemfile update adding json

add json gem to Gemfile

---

lib/vagrant-openshift/action/install_openshift.rb

Env var change.
Merge after https://github.com/openshift/origin/pull/3104

change default kubeconfig location

---

lib/vagrant-openshift/action/push_openshift_images.rb

- Fix prepending of PATH
- Push images only after all images builds && test
- Simplify the bash scripts

Improvements to the push_images job

---

lib/vagrant-openshift/action/download_artifacts_openshift.rb

Download artifacts produced by https://github.com/openshift/origin/pull/3440.

Download test-cmd.sh artifacts

---

lib/vagrant-openshift/action/install_openshift_base_dependencies.rb

In order to allow https://github.com/openshift/origin/pull/4118
@derekwaynecarr  PTAL

Add go vet to dependencies

---

README.asciidoc
lib/vagrant-openshift/action/generate_template.rb
lib/vagrant-openshift/command/openshift_init.rb
lib/vagrant-openshift/templates/command/init-openshift/box_info.yaml
lib/vagrant-openshift/version.rb

Made changes to include atomic host ami and using as a dev system

---

lib/vagrant-openshift/action/push_openshift_images.rb
lib/vagrant-openshift/command/test_openshift_image.rb

This reverts commit 562df808e2472de725bdbad9c8243c94c3751f8e.

Revert "don't rebuild images that don't have a new commit"

---

lib/vagrant-openshift/action/run_openshift_tests.rb

Depends on https://github.com/openshift/origin/pull/4658

Change how extended is invoked

---

lib/vagrant-openshift/action/build_openshift.rb

Use makefile for the release process

---

lib/vagrant-openshift/action/install_openshift_base_dependencies.rb

Required in the kubelet as of https://github.com/kubernetes/kubernetes/pull/13628
@danmcp

Install ethtool

---

lib/vagrant-openshift/action/install_openshift.rb

Fixes https://github.com/openshift/origin/issues/4820

Update openshift.service with new path

---

lib/vagrant-openshift/action/create_yum_repositories.rb
lib/vagrant-openshift/action/generate_template.rb
lib/vagrant-openshift/command/origin_init.rb
lib/vagrant-openshift/templates/command/init-openshift/box_info.yaml

This is part of https://trello.com/c/PnZHxsc8/81-3-create-rhel7-latest-devenv-ami

Adding support for rhel7next

---

lib/vagrant-openshift/action/run_origin_tests.rb

Double test timeouts to 4 hours

---

lib/vagrant-openshift/action/run_origin_tests.rb

@danmcp other changes coming to master

Generate junit test output for extended tests

---

lib/vagrant-openshift/action/run_origin_tests.rb

Ginkgo is no longer required, output env was wrong

---

lib/vagrant-openshift/action/install_origin.rb
lib/vagrant-openshift/action/install_origin_asset_dependencies.rb
lib/vagrant-openshift/action/install_origin_base_dependencies.rb
lib/vagrant-openshift/action/set_host_name.rb

@danmcp I'm going to leave this open for a few days until we get back to it

Fail harder during install tasks to flush out weakness

---

lib/vagrant-openshift/helper/command_helper.rb

previously the do_execute method was not handling the exception that was
thrown when an ssh command returned a non-zero rc.

unify sudo and do_execute methods

---

lib/vagrant-openshift/action/run_origin_tests.rb

Based on [this email](http://lists.openshift.redhat.com/openshift-archives/dev/2015-October/msg00035.html) I've modified the flag we're passing. @danmcp

Fixed the way we pass focus flag to extended tests

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb

@bparees this tool is necessary for upcoming logging integration for our test scripts

added system logging tool

---

lib/vagrant-openshift/action/run_origin_tests.rb

@bparees PTAL
@deads2k FYI
fixes https://github.com/openshift/vagrant-openshift/issues/379

removed hard-coded directories

---

lib/vagrant-openshift/action/download_artifacts_origin.rb

David doesn't like nesting. This amend the download target for https://github.com/openshift/origin/pull/6591#discussion_r50134080
@bparees PTAL
@deads2k FYI

modified download target

---

lib/vagrant-openshift/action/push_openshift_images.rb
lib/vagrant-openshift/command/test_origin_image.rb

This reverts commit 7f90e07ed8206973095815c090f06792b8a42253.

Revert "remove squashing on image building"

---

lib/vagrant-openshift/command/test_origin_image.rb

And remove reference to a long time nonexistent variable.

Set common bash options

---

lib/vagrant-openshift/action/download_artifacts_origin.rb
lib/vagrant-openshift/command/download_artifacts_origin.rb
lib/vagrant-openshift/command/test_origin.rb

remove releases from artifact downloads

---

lib/vagrant-openshift/command/test_origin_image.rb

Merge PR's branch with master before testing

---

lib/vagrant-openshift/command/test_origin_image.rb

This reverts commit ad869880cb7860b98e1cb642fb7563c2ba20e9f1.

Revert "Merge PR's branch with master before testing"

---

lib/vagrant-openshift/action/download_artifacts_origin.rb
lib/vagrant-openshift/command/download_artifacts_origin.rb
lib/vagrant-openshift/command/test_origin.rb

Reverts openshift/vagrant-openshift#410
mismatched # of args.
@stevekuznetsov fyi. @smarterclayton fyi.

Revert "remove releases from artifact downloads"

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb

Adds `ShellCheck` for linting shell files.
@bparees PTAL

added ShellCheck dep

---

README.asciidoc

The current steps are incomplete and incorrect, and this attempts to fix that. Until the error from `bundle exec rake` can be fixed, it is also useful to mention in the README that it is OK to see the error and continue.
@danmcp @bparees

added more steps to local dev for README

---

Gemfile
README.asciidoc

Addresses issue #430. Satisfy dependency from installed gem if
possible.

Fix vagrant dependency in Gemfile

---

README.asciidoc
lib/vagrant-openshift/action.rb
lib/vagrant-openshift/action/download_artifacts_origin_metrics.rb
lib/vagrant-openshift/action/run_origin_metrics_tests.rb
lib/vagrant-openshift/command/download_artifacts_origin_metrics.rb
lib/vagrant-openshift/command/repo_sync_origin_metrics.rb
lib/vagrant-openshift/command/test_origin_metrics.rb
lib/vagrant-openshift/constants.rb
lib/vagrant-openshift/plugin.rb

Add support for running tests against origin-metrics

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb

To combat:
- https://bugzilla.redhat.com/show_bug.cgi?id=1344013
- https://github.com/openshift/origin/issues/9201

Use deferred deletion and removal for Docker daemon

---

lib/vagrant-openshift/helper/command_helper.rb

The command supports -b and -u, but when --replace is specified the
command is ignored.
@danmcp

origin-local-checkout doesn't handle users properly

---

lib/vagrant-openshift/helper/command_helper.rb

This reverts commit 7e60b7741143b9b748f130a478cfa5789c337847, reversing
changes made to a50481fd16d803e4a7bb06f7bf162de65cd03b29.

Revert "Merge pull request #467 from smarterclayton/handle_branch"

---

lib/vagrant-openshift/action.rb
lib/vagrant-openshift/action/build_origin_images.rb
lib/vagrant-openshift/action/download_artifacts_origin_console.rb
lib/vagrant-openshift/action/run_origin_asset_tests.rb
lib/vagrant-openshift/command/create_local_yum_repo.rb
lib/vagrant-openshift/constants.rb
lib/vagrant-openshift/plugin.rb

fix trailing whitespace in *.rb files

---

lib/vagrant-openshift/helper/command_helper.rb

In `command_helper.rb`: Before checking out a repo, we now check it with `git fsck` and clone
from scratch if the repo is broken. This can happen when `git gc` is
terminated while the repo is in an invalid state.
This change also reintroduces the `git gc` step.

Check and fix broken repos

---

lib/vagrant-openshift/action/push_openshift_images.rb

don't push v2 schemas when building s2i images

---

lib/vagrant-openshift/action/install_origin_rhel7.rb

Added GPG keys necessary to validate RPMs installed during the
build and update processes. Removed repositories for which we
have no keys on the containers.
@danmcp PTAL -- I am going to try to get everything unrelated to the Golang/Docker stuff in so #459 doesn't become too stale

Improved RHEL7 container setup

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb

Fixes https://github.com/openshift/origin/issues/11625

Add zip dep

---

lib/vagrant-openshift/action/install_origin_base_dependencies.rb
lib/vagrant-openshift/resources/configure_docker.sh
lib/vagrant-openshift/resources/configure_system.sh
lib/vagrant-openshift/resources/dockerextra.repo
lib/vagrant-openshift/resources/install_chrome.sh
lib/vagrant-openshift/resources/install_dependencies.sh
lib/vagrant-openshift/resources/install_dockerextra_repo.sh
lib/vagrant-openshift/resources/install_golang.sh
lib/vagrant-openshift/resources/install_nonessential.sh
lib/vagrant-openshift/resources/install_rhaos_repos.sh
lib/vagrant-openshift/resources/origin-deps-rhel7.repo
lib/vagrant-openshift/resources/reconfigure_network_fedora.sh
lib/vagrant-openshift/resources/rhaos31.repo
lib/vagrant-openshift/resources/rhaos32.repo
lib/vagrant-openshift/resources/rhaos33.repo
lib/vagrant-openshift/resources/rhaos34.repo

Reverts openshift/vagrant-openshift#510

Revert "Revert "Configure `build-origin-base` to use local scripts""

---

lib/vagrant-openshift/action.rb
lib/vagrant-openshift/action/build_sti_base_windows.rb
lib/vagrant-openshift/action/clone_upstream_repositories.rb
lib/vagrant-openshift/action/download_artifacts_sti.rb
lib/vagrant-openshift/action/generate_template.rb
lib/vagrant-openshift/action/run_sti_tests.rb
lib/vagrant-openshift/aws.rb
lib/vagrant-openshift/command/build_sti_base_windows.rb
lib/vagrant-openshift/helper/command_helper.rb
lib/vagrant-openshift/hooks/configure_aws.rb
lib/vagrant-openshift/hooks/find_ami.rb
lib/vagrant-openshift/hooks/windows_wait.rb
lib/vagrant-openshift/plugin.rb
lib/vagrant-openshift/provisioner/configure_docker_client_windows.rb
lib/vagrant-openshift/provisioner/configure_docker_server_linux.rb
lib/vagrant-openshift/templates/command/init-openshift/box_info.yaml

Revert 'Revert "Enable s2i windows testing"'

---

lib/vagrant-openshift/action/build_origin_base_images.rb

https://github.com/openshift/origin/pull/12192 needs to merge first.

Bake dind images into the ami

---

lib/vagrant-openshift/resources/install_rhaos_repos.sh
lib/vagrant-openshift/resources/rhaos35.repo

Add a repository configuration file for AOS 3.5 RPMs

---

lib/vagrant-openshift/plugin.rb

Thread together new imports for Jenkins repo sync
